MvcOnlineTicariOtomasyon/Models/Siniflar/Departman.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MvcOnlineTicariOtomasyon.Models.Siniflar
{
    public class Departman
    {
        [Key]
        public int Departmanid { get; set; }
        [Column(TypeName = "Varchar")]
        [StringLength(30)]
        public string DepartmanAd {  get; set; }
        public bool Durum {  get; set; }
        public ICollection<Personel> Personels { get; set; }
    }
}

MvcOnlineTicariOtomasyon/Controllers/DepartmanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcOnlineTicariOtomasyon.Models.Siniflar;
namespace MvcOnlineTicariOtomasyon.Controllers
{
    public class DepartmanController : Controller
    {
        // GET: Departman
        Context c = new Context();
        public ActionResult Index(string p)
        {
            var degerler = from x in c.Departmans select x;
            if(!string.IsNullOrEmpty(p))
            {
                degerler = degerler.Where(y => y.DepartmanAd.Contains(p));  
            }
            return View(degerler.ToList());
        }
        [Authorize(Roles ="A")]
        [HttpGet]
        public ActionResult DepartmanEkle()
        {
            return View();
        }
        [HttpPost]
        public ActionResult DepartmanEkle(Departman d)
        {
            c.Departmans.Add(d);
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult DepartmanSil(int id)
        {
            var dep = c.Departmans.Find(id);
            dep.Durum = false;
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult DepartmanGetir (int id)
        {
            var dprt = c.Departmans.Find(id);
            return View("DepartmanGetir", dprt);
        }
        public ActionResult DepartmanGuncelle(Departman d)
        {
            var departman = c.Departmans.Find(d.Departmanid);
            departman.DepartmanAd = d.DepartmanAd;
            c.SaveChanges();
            return RedirectToAction("Index");   
        }
        public ActionResult DepartmanDetay(int id)
        {
            var degerler = c.Personels.Where(x => x.Departmanid == id).ToList();
            var dpt = c.Departmans.Where(x => x.Departmanid == id).Select(y => y.DepartmanAd).FirstOrDefault();
            ViewBag.deger1 = dpt;
            return View(degerler);
        }
        public ActionResult DepartmanPersonelSatis(int id)
        {
            var degerler = c.SatisHarekets.Where(x => x.Personelid == id).ToList();
            var per = c.Personels.Where(x => x.Personelid == id).Select(y => y.PersonelAd +" "+ y.PersonelSoyad).FirstOrDefault();
            ViewBag.deger = per;
            return View(degerler);
        }
    }
}

MvcOnlineTicariOtomasyon/Views/Departman/DepartmanDetay.cshtml
@using MvcOnlineTicariOtomasyon.Models.Siniflar
@model List<Personel>
@{
    ViewBag.Title = "DepartmanDetay";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<h2>Departman Detayları</h2>
<br />
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active">@ViewBag.deger1</li>
</ol>
<table class=" table table-hover">
    <tr>
        <th>Personel</th>
        <th>Satışlar</th>
    </tr>
    @foreach (var x in Model)
     {
        <tr>
            <td>@x.PersonelAd @x.PersonelSoyad</td>
            <td><a href="/Departman/DepartmanPersonelSatis/@x.Personelid" class="btn btn-default" style="background-color:navajowhite">Satışlar</a></td>
        </tr>
     }
</table>

MvcOnlineTicariOtomasyon/Views/Departman/DepartmanEkle.cshtml
@model MvcOnlineTicariOtomasyon.Models.Siniflar.Departman
@{
    ViewBag.Title = "DepartmanEkle";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<h2>Yeni Departman Ekle</h2>
<br />
<form class="form-group" method="post">
    <label>Departman Adı</label>
    @Html.TextBoxFor(x => x.DepartmanAd, new { @class = "form-control" })
    <br />
    <button class="btn btn-success">Departman Ekle</button>
</form>

MvcOnlineTicariOtomasyon/Views/Departman/DepartmanGetir.cshtml
@model MvcOnlineTicariOtomasyon.Models.Siniflar.Departman
@{
    ViewBag.Title = "DepartmanGetir";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<h2>Departman Güncelle</h2>
<br />
@using (Html.BeginForm("DepartmanGuncelle", "Departman", FormMethod.Post))
{
    <div class="form-group">
        @Html.HiddenFor(x => x.Departmanid)
        <label>Departman Adı</label>
        @Html.TextBoxFor(x => x.DepartmanAd, new { @class = "form-control" })
    </div>
    <button class=" btn btn-warning">Departman Güncelle</button>
}

MvcOnlineTicariOtomasyon/Views/Departman/DepartmanPersonelSatis.cshtml
@using MvcOnlineTicariOtomasyon.Models.Siniflar
@model List<SatisHareket>
@{
    ViewBag.Title = "DepartmanPersonelSatis";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<h2>Departman Personel Satış</h2>
<br />
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active">@ViewBag.deger</li>
</ol>
<table class="table table-condensed">
    <tr>
        <th>Cari</th>
        <th>Ürün</th>
        <th>Tarih</th>
        <th>Adet</th>
        <th>Fiyat</th>
        <th>Toplam Tutar</th>
        <th>Yazdır</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.Cariler.CariAd @x.Cariler.CariSoyad</td>
            <td>@x.Urun.UrunAd</td>
            <td>@x.Tarih</td>
            <td>@x.Adet</td>
            <td>@x.Fiyat</td>
            <td>@x.ToplamTutar</td>
            <td><a href="#"><i class="fas fa-print"></i></a></td>
        </tr>
    }
</table>

MvcOnlineTicariOtomasyon/Views/Departman/Index.cshtml
@using MvcOnlineTicariOtomasyon.Models.Siniflar
@model List<Departman>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<h2>Departman Listesi</h2>
<br />
@using (Html.BeginForm("Index", "Departman", FormMethod.Get))
{
    @Html.TextBox("p", null, new { @class = "form-method-me-2" })
    <button class="btn btn-outline-success" type="submit">Ara</button>
}
<br />
<table class="table table-bordered">
    <tr>
        <th>Departman Adı</th>
        <th>Detaylar</th>
        <th>Güncelle</th>
        <th>Sil</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.DepartmanAd</td>
            <td><a href="/Departman/DepartmanDetay/@x.Departmanid" class="btn btn-success">Detaylar</a></td>
            <td><a href="/Departman/DepartmanGetir/@x.Departmanid" class="btn btn-warning">Güncelle</a></td>
            <td><a href="/Departman/DepartmanSil/@x.Departmanid" class="btn btn-danger" id="btn2">Sil</a></td>
        </tr>
    }
</table>
<br />
<a href="/Departman/DepartmanEkle/" class="btn btn-primary">Departman Ekle</a>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script>
    $(document).on('click', '.btn-danger', function (event) {
        event.preventDefault();
        swal({
            title: "Emin misiniz?",
            text: "Departman silindikten sonra erişemeyeceksiniz!",
            icon: "warning",
            buttons: true,
            dangerMode: true,
        }).then((willDelete) => {
            if (willDelete) {
                swal("Departman silindi!", {
                    icon: "success",
                }).then(() => {
                    window.location.href = $(this).attr('href');
                });
            } else {
                swal("İşlem iptal edildi!");
            }
        });
    });
</script>