MvcOnlineTicariOtomasyon/Controllers/SatisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcOnlineTicariOtomasyon.Models.Siniflar;
namespace MvcOnlineTicariOtomasyon.Controllers
{
    public class SatisController : Controller
    {
        // GET: Satis
        Context c = new Context();
        public ActionResult Index()
        {
            var degerler = c.SatisHarekets.ToList();
            return View(degerler);
        }
        [HttpGet]
        public ActionResult YeniSatis()
        {
            List<SelectListItem> deger1 = (from x in c.Personels.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.PersonelAd + " " + x.PersonelSoyad,
                                               Value = x.Personelid.ToString(),
                                           }).ToList();
            List<SelectListItem> deger2 = (from x in c.Carilers.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.CariAd + " " + x.CariSoyad,
                                               Value = x.Cariid.ToString(),
                                           }).ToList();
            List<SelectListItem> deger3 = (from x in c.Uruns.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.UrunAd,
                                               Value = x.Urunid.ToString(),
                                           }).ToList();
            ViewBag.dgr1 = deger1;
            ViewBag.dgr2 = deger2;
            ViewBag.dgr3 = deger3;
            return View();
        }
        [HttpPost]
        public ActionResult YeniSatis(SatisHareket s)
        {
            s.Tarih = DateTime.Parse(DateTime.Now.ToString());
            c.SatisHarekets.Add(s);
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult SatisGetir(int id)
        {
            List<SelectListItem> deger1 = (from x in c.Personels.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.PersonelAd + " " + x.PersonelSoyad,
                                               Value = x.Personelid.ToString(),
                                           }).ToList();
            List<SelectListItem> deger2 = (from x in c.Carilers.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.CariAd + " " + x.CariSoyad,
                                               Value = x.Cariid.ToString(),
                                           }).ToList();
            List<SelectListItem> deger3 = (from x in c.Uruns.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.UrunAd,
                                               Value = x.Urunid.ToString(),
                                           }).ToList();
            ViewBag.dgr1 = deger1;
            ViewBag.dgr2 = deger2;
            ViewBag.dgr3 = deger3;
            var sts = c.SatisHarekets.Find(id);
            return View("SatisGetir", sts);
        }
        public ActionResult SatisGuncelle(SatisHareket st)
        {
            var satis = c.SatisHarekets.Find(st.Satisid);
            satis.Tarih = st.Tarih;
            satis.Cariid = st.Cariid;
            satis.Fiyat = st.Fiyat; 
            satis.Adet = st.Adet;
            satis.Personelid = st.Personelid;   
            satis.ToplamTutar = st.ToplamTutar;
            satis.Urunid = st.Urunid;
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult SatisDetay(int id)
        {
            var degerler = c.SatisHarekets.Where(x => x.Satisid == id).ToList();
            return View(degerler);
        }
    }
}

MvcOnlineTicariOtomasyon/Views/Satis/Index.cshtml
@using MvcOnlineTicariOtomasyon.Models.Siniflar
@model List<SatisHareket>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<h2>Satış Listesi</h2>
<br />
<table id="tbl1" class="table table-condensed">
    <thead>
        <tr>
            <th>Satış ID</th>
            <th>Tarih</th>
            <th>Personel</th>
            <th>Cari</th>
            <th>Ürün</th>
            <th>Adet</th>
            <th>Fiyat</th>
            <th>Toplam Tutar</th>
            <th>Güncelle</th>
            <th>Detaylar</th>
        </tr>
    </thead>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.Satisid</td>
            <td>@x.Tarih</td>
            <td>@x.Personel.PersonelAd @x.Personel.PersonelSoyad</td>
            <td>@x.Cariler.CariAd @x.Cariler.CariSoyad</td>
            <td>@x.Urun.UrunAd</td>
            <td>@x.Adet</td>
            <td>@x.Fiyat</td>
            <td>@x.ToplamTutar</td>
            <td><a href="/Satis/SatisGetir/@x.Satisid" class="btn btn-warning">Güncelle</a></td>
            <td><a href="/Satis/SatisDetay/@x.Satisid" class="btn btn-success">Detaylar</a></td>
        </tr>
    }
</table>
<a href="/Satis/YeniSatis" class="btn btn-primary">Yeni Satış Yap</a>
@*<link href="~/Content/bootstrap.css" rel="stylesheet" />*@

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>




<link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css" rel="stylesheet" />
<script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap4.min.js "></script>

<script>
    $('#tbl1').dataTable({});
</script>

MvcOnlineTicariOtomasyon/Views/Satis/SatisDetay.cshtml
@using MvcOnlineTicariOtomasyon.Models.Siniflar
@model List<SatisHareket>
@{
    ViewBag.Title = "SatisDetay";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<h2>Satış Detay</h2>
<br />
<table class="table table-condensed">
    <tr>
        <th>Satış ID</th>
        <th>Tarih</th>
        <th>Personel</th>
        <th>Cari</th>
        <th>Ürün</th>
        <th>Adet</th>
        <th>Fiyat</th>
        <th>Toplam Tutar</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.Satisid</td>
            <td>@x.Tarih</td>
            <td>@x.Personel.PersonelAd @x.Personel.PersonelSoyad</td>
            <td>@x.Cariler.CariAd @x.Cariler.CariSoyad</td>
            <td>@x.Urun.UrunAd</td>
            <td>@x.Adet</td>
            <td>@x.Fiyat</td>
            <td>@x.ToplamTutar</td>
            <td><a href="#"><i class="fas fa-print"></i></a></td>
        </tr>
    }
</table>

MvcOnlineTicariOtomasyon/Views/Satis/SatisGetir.cshtml
@model MvcOnlineTicariOtomasyon.Models.Siniflar.SatisHareket
@{
    ViewBag.Title = "SatisGetir";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<h2>Satış Güncelle</h2>
<br />
@using (Html.BeginForm("SatisGuncelle", "Satis", FormMethod.Post))
{
    @Html.HiddenFor(x => x.Satisid)
    <label>Personel</label>
    @Html.DropDownListFor(x => x.Personelid, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
    <br />
    <label>Cari</label>
    @Html.DropDownListFor(x => x.Cariid, (List<SelectListItem>)ViewBag.dgr2, new { @class = "form-control" })
    <br />
    <label>Ürün</label>
    @Html.DropDownListFor(x => x.Urunid, (List<SelectListItem>)ViewBag.dgr3, new { @class = "form-control" })
    <br />
    <label>Adet</label>
    @Html.TextBoxFor(x => x.Adet, new { @class = "form-control" })
    <br />
    <label>Fiyat</label>
    @Html.TextBoxFor(x => x.Fiyat, new { @class = "form-control" })
    <br />
    <label>Toplam Tutar</label>
    @Html.TextBoxFor(x => x.ToplamTutar, new { @class = "form-control" })
    <br />
    <label>Tarih</label>
    @Html.TextBoxFor(x => x.Tarih, new { @class = "form-control" })
    <br />
    <button class="btn btn-success">Satış Güncelle</button>
}

MvcOnlineTicariOtomasyon/Views/Satis/YeniSatis.cshtml
@model MvcOnlineTicariOtomasyon.Models.Siniflar.SatisHareket
@{
    ViewBag.Title = "YeniSatis";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<h2>Yeni Satış Yap</h2>
<br />
<form class="form-group" method="post">
    <label>Personel</label>
    @Html.DropDownListFor(x => x.Personelid, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
    <br />
    <label>Cari</label>
    @Html.DropDownListFor(x => x.Cariid, (List<SelectListItem>)ViewBag.dgr2, new { @class = "form-control" })
    <br />
    <label>Ürün</label>
    @Html.DropDownListFor(x => x.Urunid, (List<SelectListItem>)ViewBag.dgr3, new { @class = "form-control" })
    <br />
    <label>Adet</label>
    @Html.TextBoxFor(x => x.Adet, new { @class = "form-control" })
    <br />
    <label>Fiyat</label>
    @Html.TextBoxFor(x => x.Fiyat, new { @class = "form-control" })
    <br />
    <label>Toplam Tutar</label>
    @Html.TextBoxFor(x => x.ToplamTutar, new { @class = "form-control" })
    <br />
    <button class="btn btn-success">Yeni Satış Yap</button>
</form>