MvcOnlineTicariOtomasyon/Models/Siniflar/KargoTakip.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MvcOnlineTicariOtomasyon.Models.Siniflar
{
    public class KargoTakip
    {
        [Key]
        public int KargoTakipid { get; set; }
        [Column(TypeName ="Varchar")]
        [StringLength(10)]
        public string TakipKodu { get; set; }
        [Column(TypeName = "Varchar")]
        [StringLength(100)]
        public string Aciklama { get; set; }
        public DateTime TarihZaman {  get; set; } 
        
    }
}

MvcOnlineTicariOtomasyon/Controllers/KargoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcOnlineTicariOtomasyon.Models.Siniflar;
namespace MvcOnlineTicariOtomasyon.Controllers
{
    public class KargoController : Controller
    {
        // GET: Kargo
        Context c = new Context();
        public ActionResult Index(string p)
        {
            var degerler = from x in c.KargoDetays select x;
            if(!string.IsNullOrEmpty(p) )
            {
                degerler = degerler.Where(y => y.TakipKodu.Contains(p));
            }
            return View(degerler.ToList());
        }
        [HttpGet]
        public ActionResult KargoEkle()
        {
            Random rnd = new Random();
            string[] karakterler = { "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "R", "S", "T" };
            int k1, k2, k3;
            k1 = rnd.Next(0, karakterler.Length);
            k2 = rnd.Next(0, karakterler.Length);
            k3 = rnd.Next(0, karakterler.Length);
            int s1, s2, s3;
            s1 = rnd.Next(100, 1000);
            s2 = rnd.Next(10, 99);
            s3 = rnd.Next(10, 99);
            string kod = s1 + karakterler[k1] + s2 + karakterler[k2] + s3 + karakterler[k3];
            ViewBag.takipkod = kod;
            return View();
        }
        [HttpPost]
        public ActionResult KargoEkle(KargoDetay k)
        {
            c.KargoDetays.Add(k);
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult KargoTakip(string id)
        {
            var degerler = c.KargoTakips.Where(x => x.TakipKodu == id).ToList();
            return View(degerler);
        }
    }
}

MvcOnlineTicariOtomasyon/Views/Kargo/Index.cshtml
@using MvcOnlineTicariOtomasyon.Models.Siniflar
@model List<KargoDetay>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<h2>Kargolar</h2>
@using (Html.BeginForm("Index", "Kargo", FormMethod.Get))
{
    @Html.TextBox("p", null, new { @class = "form-control-me-2" })
    <button class="btn btn-outline-success" type="submit">Ara</button>
}
<br />
<table class="table table-bordered">
    <tr>
        <th>Kargo Takip Kodu</th>
        <th>Personel</th>
        <th>Alıcı</th>
        <th>Tarih</th>
        <th>Detaylar</th>
        <th>QR Oluştur</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.TakipKodu</td>
            <td>@x.Personel</td>
            <td>@x.Alici</td>
            <td>@x.Tarih</td>
            <td><a href="/Kargo/KargoTakip/@x.TakipKodu" class="btn btn-success">Detaylar</a></td>
            <td><a href="#" class="btn btn-success" data-toggle="modal" data-id="@x.TakipKodu" data-target="#Modal1"><i class="fas fa-qrcode"></i></a></td>
        </tr>
    }
</table>
<br />
<a href="/Kargo/KargoEkle" class="btn btn-primary">Yeni Kargo Girişi</a>

<div class="modal fade" id="Modal1" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title">QR Kod Oluştur</h2>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="qrForm">
                    <input type="text" name="kod" id="kod" class="form-control" placeholder="Kargo Takip Kodu" />
                    <br />
                    <button type="submit" class="btn btn-primary">QR Kod Oluştur</button>
                </form>
                <br />
                <div id="qrResult">
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Kapat</button>
            </div>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $('#qrForm').on('submit', function (e) {
        e.preventDefault(); 

        $.ajax({
            url: '/QR/Partial1', 
            type: 'POST',
            data: $(this).serialize(), 
            success: function (data) {
                $('#qrResult').html(data);
            },
            error: function () {
                alert('Bir hata oluştu. Lütfen tekrar deneyin.');
            }
        });
    });
</script>
<script>
    $(document).on('click', '.btn-success', function () {
        var takipnumarasi = $(this).data('id');
        $('#kod').val(takipnumarasi);
    });
</script>

MvcOnlineTicariOtomasyon/Views/Kargo/KargoEkle.cshtml
@model MvcOnlineTicariOtomasyon.Models.Siniflar.KargoDetay
@{
    ViewBag.Title = "KargoEkle";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<h2>Yeni Kargo Girişi</h2>
<br />
<form class="form-group" method="post">
    <label>Kargo Takip Kodu</label>
    <input type="text" name="TakipKodu" value="@ViewBag.takipkod" class="form-control" readonly />
    <br />
    <label>Personel</label>
    @Html.TextBoxFor(x => x.Personel, new { @class = "form-control" })
    <br />
    <label>Alıcı</label>
    @Html.TextBoxFor(x => x.Alici, new { @class = "form-control" })
    <br />
    <label>Tarih</label>
    <input type="date" name="Tarih" class="form-control" />
    <br />
    <label>Açıklama</label>
    @Html.TextAreaFor(x => x.Aciklama, new { @class = "form-control" })
    <br />
    <button class="btn btn-success">Kargo Ekle</button>
</form>

MvcOnlineTicariOtomasyon/Views/Kargo/KargoTakip.cshtml
@using MvcOnlineTicariOtomasyon.Models.Siniflar
@model List<KargoTakip>
@{
    ViewBag.Title = "KargoTakip";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Kargo Detayları</h2>
<br />
<table class="table table-striped">
    <tr>
        <th>Açıklama</th>
        <th>Tarih</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.Aciklama</td>
            <td>@x.TarihZaman</td>
        </tr>
    }
</table>
<br />